####################################################
# Computational Methods for Economists using Python,
# Jupyter Book documentation settings
####################################################
title : Computational Methods for Economists using Python
author : Richard W. Evans
copyright : '2023'
logo : '..//CompMethodsLogo.png'

####################################################
# Execution settings
execute:
  execute_notebooks: force
  timeout: -1

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
    - html_image
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

####################################################
# HTML-specific settings
html:
  favicon                : "..//favicon.ico"  # A path to a favicon image
  use_edit_page_button   : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button  : true  # Whether to add a link to your repository button
  use_issues_button      : true  # Whether to add an "open an issue" button
  use_multitoc_numbering : true   # Continuous numbering across parts/chapters
  extra_navbar           : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer           : ""  # Will be displayed underneath the footer.
  google_analytics_id    : ""  # A GA id that can be used to track book views.
  home_page_in_navbar    : true  # Whether to include your home page in the left Navigation Bar
  # baseurl                : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # analytics:
  # comments:
  #   hypothesis           : false
  #   utterances           : false
  # announcement           : "" # A banner announcement at the top of the site.

#######################################################################################
# LaTeX and BibTex settings
latex:
  latex_engine          : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex : true  # use sphinx-jupyterbook-latex for pdf builds as default

bibtex_bibfiles:
   - CompMethods_references.bib
####################################################
# Launch button settings
launch_buttons:
  notebook_interface     : 'classic'  # The interface interactive links will activate ["classic", "jupyterlab"]
  # binderhub_url          : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  # jupyterhub_url         : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  # thebelab               : false  # Add a thebelab button to pages (requires the repository to run on Binder)
  colab_url          : "" # The URL of Google Colab (https://colab.research.google.com)

#######################################################################################
# FiscalSim-US repository settings
repository:
  url: https://github.com/OpenSourceEcon/CompMethods
  branch: main
  path_to_book: "docs/book"

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          : ['sphinx.ext.autodoc', 'sphinx.ext.mathjax',
                               'sphinx.ext.viewcode', 'sphinx.ext.napoleon',
                               'alabaster']   # A list of extra extensions to load by Sphinx.
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
    bibtex_reference_style: author_year
    mathjax_path          : https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#######################################################################################
# Advanced Sphinx settings
sphinx:
  extra_extensions: ['sphinx.ext.autodoc', 'sphinx.ext.mathjax',
                     'sphinx.ext.viewcode', 'sphinx.ext.napoleon',
                     'alabaster', 'sphinx_exercise']  # A list of extra extensions to load by Sphinx.
  config:  # key-value pairs to directly over-ride the Sphinx configuration
    bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    # html_theme: furo
    pygments_style: default
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinxarg.ext"
    - "sphinx.ext.viewcode"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.mathjax"
    - "sphinx_exercise"
