
name: Check code formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: psf/black@stable
        with:
          options: "-l 79 --check"
          src: "."
